# Generated by Django 6.0.4 on 2026-04-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation_latitude_donation_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='collection_address',
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='postcode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='street_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
